---
# These tasks install PHPStorm

- name: Copy in PHPStorm
  synchronize:
    src: PhpStorm-{{ PHPSTORM_FULL_VERSION }}
    dest: "/opt/phpstorm"
    owner: false
    use_ssh_args: true

- name: Copy in PHPStorm config
  synchronize:
    src: PhpStorm{{ PHPSTORM_VERSION }}
    dest: "/home/domjudge/.config/JetBrains"
    owner: false
    use_ssh_args: true

- name: Copy in PHPStorm jdbc drivers
  synchronize:
    src: jdbc-drivers
    dest: "/home/domjudge/.config/JetBrains/PhpStorm{{ PHPSTORM_VERSION }}/"
    owner: false
    use_ssh_args: true

- name: fix ownership of PHPStorm config
  file:
    path: "/home/domjudge/.config/JetBrains/PhpStorm{{ PHPSTORM_VERSION }}"
    recurse: true
    owner: domjudge
    group: domjudge

- name: Create local directory
  become: true
  become_user: domjudge
  file:
    path: "/home/domjudge/.local/share/JetBrains/"
    state: directory
    mode: '0755'

- name: Copy in PHPStorm local share
  synchronize:
    src: PhpStorm{{ PHPSTORM_VERSION }}-local-share/
    dest: "/home/domjudge/.local/share/JetBrains/PhpStorm{{ PHPSTORM_VERSION }}"
    owner: false
    recursive: true
    use_ssh_args: true

- name: fix ownership of PHPStorm local share
  file:
    path: "/home/domjudge/.local/share/JetBrains/PhpStorm{{ PHPSTORM_VERSION }}"
    recurse: true
    owner: domjudge
    group: domjudge

- name: Copy in PHPStorm settings for repo
  synchronize:
    src: .idea
    dest: "{{ DJ_DIR }}"
    owner: false
    use_ssh_args: true

- name: fix ownership of PHPStorm config
  file:
    path: "{{ DJ_DIR }}/.idea"
    recurse: true
    owner: domjudge
    group: domjudge

- name: Create a directory if it does not exist
  become: true
  become_user: domjudge
  file:
    path: /home/domjudge/.local/share/applications
    state: directory
    mode: '0755'

- name: Copy in PHPStorm Desktop icon
  become: true
  become_user: domjudge
  template:
    src: jetbrains-phpstorm.desktop.j2
    dest: /home/domjudge/.local/share/applications/jetbrains-phpstorm.desktop
    mode: 0644
