---
# These tasks create a checkout of the DOMjudge repo

- name: create working copy directory
  file:
    path: "{{ DJ_DIR }}"
    state: directory
    owner: domjudge
    group: domjudge
    mode: 0755

- name: Update repo URL based on network
  set_fact:
    dj_git_repo: "{{ DJ_GIT_REPO_RESTRICTED if WF_RESTRICTED_NETWORK else DJ_GIT_REPO }}"

- name: Create working copy of the domjudge repo
  become: true
  become_user: domjudge
  git: repo={{ dj_git_repo }} dest={{ DJ_DIR }} version={{ DJ_BRANCH }} accept_hostkey=yes update=yes
  register: git_working_copy

- name: Check composer dependencies present
  become: false
  delegate_to: localhost
  stat:
    path: files/lib/vendor
  register: libvendor

- name: Copy in composer dependencies (if they exist locally)
  synchronize:
    src: files/lib/vendor/
    dest: "{{ DJ_DIR }}/lib/vendor/"
    owner: false
    use_ssh_args: true
  when: libvendor.stat.exists

- name: fix ownership of lib/vendor
  file:
    path: "{{ DJ_DIR }}/lib/vendor"
    recurse: true
    owner: domjudge
    group: domjudge
