---
# These tasks create a checkout of the DOMjudge repo

- name: Create working copy directory
  file:
    path: "{{ DJ_DIR }}"
    state: directory
    owner: domjudge
    group: domjudge
    mode: 0755

- name: Create ansible tmp directory
  file:
    path: /home/domjudge/.ansible/tmp
    state: directory
    owner: domjudge
    group: domjudge
    mode: 0755

- name: Update repo URL based on network
  set_fact:
    dj_git_repo: "{{ DJ_GIT_REPO_RESTRICTED if WF_RESTRICTED_NETWORK else DJ_GIT_REPO }}"

- name: Create working copy of the domjudge repo
  become: true
  become_user: domjudge
  git:
    repo: "{{ dj_git_repo }}"
    dest: "{{ DJ_DIR }}"
    version: "{{ DJ_BRANCH }}"
    accept_hostkey: true
    update: true
    force: "{{ DJ_FORCE_UPDATE }}"
  register: git_working_copy

- name: Install composer dependencies
  when: WF_RESTRICTED_NETWORK
  block:
    - name: Check composer dependencies present
      become: false
      delegate_to: localhost
      stat:
        path: roles/domjudge_checkout/files/webapp/vendor
      register: vendor
      check_mode: no

    - name: Copy in composer dependencies (if they exist locally)
      synchronize:
        src: files/webapp/vendor/
        dest: "{{ DJ_DIR }}/webapp/vendor/"
        owner: false
        use_ssh_args: true
      when: vendor.stat.exists

    - name: Fix ownership of webapp/vendor
      file:
        path: "{{ DJ_DIR }}/webapp/vendor"
        recurse: true
        owner: domjudge
        group: domjudge
