---
# These tasks install and configure a MySQL server

- name: install mysql packages
  apt:
    state: present
    pkg:
      - mariadb-server
      - python3-mysqldb
      - mycli

- name: copy in MySQL config
  synchronize:
    src: my.cnf
    dest: /root/.my.cnf
    perms: false
    owner: false
    group: false

- name: Set file permissions for MySQL config
  file:
    path: /root/.my.cnf
    mode: 0644
    owner: root
    group: root

- name: create directory for systemd mysql settings
  file:
    path: /etc/systemd/system/mysql.service.d/
    state: directory
    group: root
    owner: root
    mode: 0755

- name: update systemd so mysql has bigger limits
  synchronize:
    src: mysql.override.cnf
    dest: /etc/systemd/system/mysql.service.d/override.conf
    perms: false
    group: false
    owner: false
  notify: restart mysql

- name: set mysql memory limits file
  file:
    dest: /etc/systemd/system/mysql.service.d/override.conf
    mode: 0644
    group: root
    owner: root
  notify: restart mysql

- name: add mysql config snippet to increase limits
  synchronize:
    src: mysql.domjudge.cnf
    dest: /etc/mysql/mariadb.conf.d/zz_domjudge.cnf
    perms: false
    owner: false
    group: false
  notify: restart mysql

- name: set increased limits permissions
  file:
    dest: /etc/mysql/mariadb.conf.d/zz_domjudge.cnf
    mode: 0644
    owner: root
    group: root
  notify: restart mysql

- name: make sure mysql is restarted
  meta: flush_handlers

- name: create directory to store scripts & database dumps
  file:
    path: /home/domjudge/{{ item }}
    owner: domjudge
    group: domjudge
    state: directory
    mode: 0755
  loop:
    - db-dumps
    - bin

- name: copy database dump/load scripts
  synchronize:
    src: "{{ item }}"
    dest: /home/domjudge/bin/{{ item }}
    owner: false
    group: false
    perms: false
  loop:
    - load-db
    - dump-db

- name: copy database dump/load scripts
  file:
    path: /home/domjudge/bin/{{ item }}
    owner: domjudge
    group: domjudge
    mode: 0755
  loop:
    - load-db
    - dump-db
