---
# These tasks install and configure a MySQL server

- name: Install mysql packages
  apt:
    state: present
    pkg:
      - mariadb-server
      - python3-mysqldb
      - mycli

- name: Copy in MySQL config
  copy:
    src: my.cnf
    dest: /root/.my.cnf
    mode: 0644
    owner: root
    group: root

- name: Create directory for systemd mysql settings
  file:
    path: /etc/systemd/system/mysql.service.d/
    state: directory
    group: root
    owner: root
    mode: 0755

- name: Update systemd so mysql has bigger limits
  copy:
    src: mysql.override.cnf
    dest: /etc/systemd/system/mysql.service.d/override.conf
    mode: 0644
    group: root
    owner: root
  notify: Restart mysql

- name: Add mysql config snippet to increase limits
  copy:
    src: mysql.domjudge.cnf
    dest: /etc/mysql/mariadb.conf.d/zz_domjudge.cnf
    mode: 0644
    owner: root
    group: root
  notify: Restart mysql

- name: Make sure mysql is restarted
  meta: flush_handlers

- name: Make sure mysql runs
  service:
    name: mysql
    state: started

- name: Create directory to store scripts & database dumps
  file:
    path: /home/domjudge/{{ item }}
    owner: domjudge
    group: domjudge
    state: directory
    mode: 0755
  loop:
    - db-dumps
    - bin

- name: Copy database dump/load scripts
  copy:
    src: "{{ item }}"
    dest: /home/domjudge/bin/{{ item }}
    owner: domjudge
    group: domjudge
    mode: 0755
  loop:
    - load-db
    - dump-db
