---
# These tasks install domlogo

- name: Install python3 modules and imagemagick for domlogo
  apt:
    state: present
    pkg:
      - python3-tk
      - imagemagick

- name: Install domlogo
  copy:
    src: domlogo.py
    dest: "{{ DJ_DIR }}"
    owner: domjudge
    group: domjudge
    mode: 0755

- name: Install domlogo Python libraries
  synchronize:
    src: lib
    dest: /home/domjudge/.local/
    owner: false
    use_ssh_args: true

- name: Fix ownership of domlogo env
  file:
    path: "/home/domjudge/.local/lib/python3.10"
    recurse: true
    owner: domjudge
    group: domjudge

- name: Install domlogo images
  synchronize:
    src: images/
    dest: "{{ DJ_DIR }}/domlogo-files/"
    owner: false
    use_ssh_args: true

- name: Fix ownership of domlogo images
  file:
    path: "{{ DJ_DIR }}/domlogo-files"
    recurse: true
    owner: domjudge
    group: domjudge

- name: Add autostart shortcuts
  template:
    src: "domjudgelogo.desktop.j2"
    dest: "/home/domjudge/.config/autostart/domjudgelogo.desktop"
    owner: domjudge
    group: domjudge
    mode: 0755
