---
# These tasks install domlogo

- name: Install python3 modules for domlogo
  apt:
    state: present
    pkg:
      - python3-tk

- name: Install domlogo and showhost
  copy:
    src: "{{ item }}.py"
    dest: "{{ DJ_DIR }}"
    owner: domjudge
    group: domjudge
    mode: 0755
  loop:
    - domlogo
    - showhost

- name: Install domlogo and showhost env
  synchronize:
    src: lib
    dest: /home/domjudge/.local/
    owner: false
    use_ssh_args: true

- name: Fix ownership of domlogo and showhost env
  file:
    path: "/home/domjudge/.local/lib/python3.8"
    recurse: true
    owner: domjudge
    group: domjudge

- name: Install domlogo images
  synchronize:
    src: images/
    dest: "{{ DJ_DIR }}/domlogo-files/"
    owner: false
    use_ssh_args: true

- name: Fix ownership of domlogo images
  file:
    path: "{{ DJ_DIR }}/domlogo-files"
    recurse: true
    owner: domjudge
    group: domjudge

- name: Add autostart shortcuts
  template:
    src: "{{ item }}.desktop.j2"
    dest: "/home/domjudge/.config/autostart/{{ item }}.desktop"
    owner: domjudge
    group: domjudge
    mode: 0755
  loop:
    - domjudgelogo
    - showhost
    - cpu-speed-fix