---
# Define here handlers associated to this role.

- name: restart cds
  systemd:
    name: cds
    enabled: true
    state: restarted
    daemon_reload: true

- name: restart nginx
  systemd:
    name: nginx
    enabled: true
    state: restarted
    daemon_reload: true
