---
# Tasks to build DOMjudge

- name: Add the restapi secret file
  template:
    src: restapi.secret.j2
    dest: "{{ DJ_DIR }}/etc/restapi.secret"
    owner: domjudge
    group: domjudge
    mode: 0600

- name: Run inplace-conf
  become: true
  become_user: domjudge
  command: make inplace-conf CONFIGURE_FLAGS='--disable-doc-build --with-baseurl={{ DOMSERVER }}/'
  register: dj_configured
  args:
    chdir: "{{ DJ_DIR }}"
    creates: "{{ DJ_DIR }}/paths.mk"

- name: Check if domjudge is built
  stat: path="{{ DJ_DIR }}/judge/judgedaemon"
  register: judgedaemon_binary
  check_mode: no

- name: Build domjudge
  become: true
  become_user: domjudge
  command: make inplace-install
  args:
    chdir: "{{ DJ_DIR }}"
  notify:
    - Fix permissions on domjudge inplace-install
    - Fix composer autoload
  when: (git_working_copy is defined and git_working_copy.changed) or dj_configured.changed or not judgedaemon_binary.stat.exists

- name: Copy domjudge-sudoers file
  copy:
    remote_src: true
    src: "{{ DJ_DIR }}/etc/sudoers-domjudge"
    dest: /etc/sudoers.d/domjudge
    mode: 0440
    owner: root
    group: root

- name: Configure domjudge logging
  copy:
    src: rsyslog.domjudge.conf
    dest: /etc/rsyslog.d/domjudge.conf
    mode: 0644
    group: root
    owner: root
  notify: Restart rsyslog

- name: Configure domjudge logrotate
  copy:
    src: logrotate.domjudge
    dest: /etc/logrotate.d/domjudge
    mode: 0644
    group: root
    owner: root
