---
# These tasks configure a static scoreboard

- name: create directories for styling, scripts, fonts and flags
  file:
    path: /home/domjudge/scoreboard/{{ item }}
    state: directory
    owner: domjudge
    group: domjudge
    mode: 0755
  loop:
    - css
    - js
    - webfonts
    - flags

- name: download required assets
  get_url:
    url: "{{ DOMSERVER_URL }}/{{ item }}"
    dest: /home/domjudge/scoreboard/{{ item }}
    owner: domjudge
    group: domjudge
    mode: 0644
  loop:
    - favicon.ico
    - css/bootstrap.min.css
    - css/fontawesome-all.min.css
    - js/jquery.min.js
    - js/bootstrap.bundle.min.js
    - js/domjudge.js
    - style_domjudge.css
    - webfonts/fa-brands-400.ttf
    - webfonts/fa-brands-400.woff2
    - webfonts/fa-regular-400.ttf
    - webfonts/fa-regular-400.woff2
    - webfonts/fa-solid-900.ttf
    - webfonts/fa-solid-900.woff2
    - webfonts/fa-v4compatibility.ttf
    - webfonts/fa-v4compatibility.woff2

- name: install contest images
  synchronize:
    src: files/domjudge-public/
    dest: "/home/domjudge/scoreboard/"
    owner: false
    use_ssh_args: true
  become: true
  become_user: domjudge

- name: download and unpack flag icons package
  unarchive:
    src: https://github.com/lipis/flag-icons/archive/refs/tags/3.5.0.zip
    dest: /tmp
    remote_src: true
    owner: domjudge
    group: domjudge

- name: copy flag icon SVG's
  copy:
    src: /tmp/flag-icons-3.5.0/flags/
    dest: /home/domjudge/scoreboard/flags/
    remote_src: true
    owner: domjudge
    group: domjudge
    mode: 0755

- name: create bin directory
  file:
    path: /home/domjudge/bin
    state: directory
    owner: domjudge
    group: domjudge
    mode: 0755

- name: install update scoreboard script
  template:
    src: update-scoreboard.sh.j2
    dest: "/home/domjudge/bin/update-scoreboard.sh"
    owner: domjudge
    group: domjudge
    mode: 0755

# Ansible cron task defaults to * for all cron parts
- name: set up cron to update scoreboard
  cron:
    name: update public scoreboard
    job: /home/domjudge/bin/update-scoreboard.sh
    user: domjudge

- name: install nginx
  apt:
    state: present
    pkg:
      - nginx

- name: add scoreboard nginx conf
  template:
    src: scoreboard.conf.j2
    dest: /etc/nginx/sites-available/scoreboard.conf
    mode: 0644
  notify: restart nginx

- name: enable nginx conf for static scoreboard
  file:
    src: /etc/nginx/sites-available/scoreboard.conf
    dest: /etc/nginx/sites-enabled/scoreboard.conf
    state: link
  notify: restart nginx

- name: disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
