# This is an example configuration file for displaying documentation links in
# the team interface.

# This file should contain an array with items to show.


- name: DOMjudge Team Guide
  link: ../docs/WFDhaka-domjudge-team-manual.pdf
  icon: fas fa-users
- name: Judging Notes
  link: ../docs/2021Dhaka.JudgingNotes.A4.pdf
  icon: fas fa-gavel
- name: Judging Notes Addendum
  link: ../docs/2021Dhaka.JudgingNotesAddendum.A4.pdf
  icon: fas fa-plus
- name: Tech Notes
  link: ../docs/2021Dhaka.TechNotes.A4.pdf
  icon: fas fa-cog
