---
# These tasks install and configure grafana

- name: install dependencies
  apt:
    state: present
    install_recommends: no
    pkg:
      - nginx
      - prometheus

# Setup Prometheus, which scrapes all metrics from the monitored machines
# The client exposes the metrics (on different ports/URIs) and we collect those
- name: set up prometheus scrapes
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: restart prometheus
  service: name=prometheus state=restarted

## Setup grafana
- name: configure grafana
  synchronize:
    src: files/grafana/environment
    dest: /etc/default/grafana-server

- name: set up grafana datasources
  synchronize:
    src: files/grafana/datasources.yml
    dest: /etc/grafana/provisioning/datasources/default.yml

- name: set up grafana dashboards
  synchronize:
    src: files/grafana/dashboards.yml
    dest: /etc/grafana/provisioning/dashboards/default.yml

- name: copy grafana dashboards
  synchronize:
    src: dashboards/
    dest: /etc/grafana/dashboards/

- name: restart grafana
  service: name=grafana-server state=restarted

# Setup nginx with selfsigned certificate
- name: copy ssl cert
  synchronize:
    src=ssl.crt
    dest=/etc/ssl/certs/grafana.crt

- name: copy ssl key
  synchronize:
    src=ssl.key
    dest=/etc/ssl/private/grafana.key

- name: copy default nginx config
  synchronize:
    src=nginx.conf
    dest=/etc/nginx/sites-enabled/grafana.conf

- name: restart nginx
  service: name=nginx enabled=yes state=restarted
