{
 "title": "Keith's DOMjudge Dashboard (Prometheus + AWS Cloudwatch)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "CLOUDFRONT_DISTRIBUTION_ID", "query": "E3BTJUDVHKRXHA" },
   { "name": "RDS_DATABASE_ID", "query": "srfg00xensrkea" },
   {
    "name": "ELB_ID",
    "query": "ser2019-WebserverE-HIF6KZ6HQJMQ"
   },
   {
    "name": "contest",
    "query": {
     "query": "label_values(domjudge_teams,contest)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "# Teams Logged In",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(domjudge_teams_logged_in{contest=~'$contest'} / domjudge_teams{contest=~'$contest'}) * 100",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "# Teams Submitted",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(domjudge_teams_submitted{contest=~'$contest'} / domjudge_teams{contest=~'$contest'}) * 100",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "# Teams Solved >0 Prob",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(domjudge_teams_correct{contest=~'$contest'} / domjudge_teams{contest=~'$contest'}) * 100",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "Submission Statistics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "domjudge_submissions_total{contest=~'$contest'}",
     "legendFormat": "{{contest}} total"
    },
    {
     "expr": "domjudge_submissions_correct{contest=~'$contest'}",
     "legendFormat": "{{contest}} correct"
    }
   ]
  },
  {
   "title": "Judging Queue Size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(domjudge_submissions_queued{contest=~'$contest'}) by (contest)",
     "legendFormat": "{{contest}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{job=\"web\",mode=\"idle\"}[5m])) * 100)\n",
     "legendFormat": "web-{{instance}}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{job=\"judge\",mode=\"idle\"}[5m])) * 100)\n",
     "legendFormat": "judge-{{instance}}"
    }
   ]
  },
  {
   "title": "#Web Hosts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HealthyHostCount",
     "dimensions": { "LoadBalancerName": "$ELB_ID" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "UnHealthyHostCount",
     "dimensions": { "LoadBalancerName": "$ELB_ID" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Cloudfront Requests",
     "dimensions": { "DistributionId": "$CLOUDFRONT_DISTRIBUTION_ID", "Region": "Global" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "period": "60",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "ELB Requests",
     "dimensions": { "LoadBalancerName": "$ELB_ID" },
     "metricName": "RequestCount",
     "namespace": "AWS/ELB",
     "period": "60",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "DB CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU Utilization",
     "dimensions": { "DBInstanceIdentifier": "$RDS_DATABASE_ID" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "WriteLatency",
     "dimensions": { "DBInstanceIdentifier": "$RDS_DATABASE_ID" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "ReadLatency",
     "dimensions": { "DBInstanceIdentifier": "$RDS_DATABASE_ID" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Extra Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "ELB Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HTTPCode_Backend_4XX",
     "dimensions": { "LoadBalancerName": "$ELB_ID" },
     "metricName": "HTTPCode_Backend_4XX",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "HTTPCode_Backend_5XX",
     "dimensions": { "LoadBalancerName": "$ELB_ID" },
     "metricName": "HTTPCode_Backend_5XX",
     "namespace": "AWS/ELB",
     "region": "default",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Cloudfront Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "4xxErrorRate",
     "dimensions": { "DistributionId": "$CLOUDFRONT_DISTRIBUTION_ID", "Region": "Global" },
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "5xxErrorRate",
     "dimensions": { "DistributionId": "$CLOUDFRONT_DISTRIBUTION_ID", "Region": "Global" },
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "TotalErrorRate",
     "dimensions": { "DistributionId": "$CLOUDFRONT_DISTRIBUTION_ID", "Region": "Global" },
     "metricName": "TotalErrorRate",
     "namespace": "AWS/CloudFront",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Mysql Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections",
     "legendFormat": "current"
    },
    {
     "expr": "mysql_global_variables_max_connections",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "mysql  disk reads vs writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_innodb_data_reads[10m])",
     "legendFormat": "reads"
    },
    {
     "expr": "irate(mysql_global_status_innodb_data_writes[10m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "DB Free Memory/Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "FreeableMemory",
     "dimensions": { "DBInstanceIdentifier": "$RDS_DATABASE_ID" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "FreeStorageSpace",
     "dimensions": { "DBInstanceIdentifier": "$RDS_DATABASE_ID" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Query rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_commands_total[5m]) > 0",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "mysql network received vs sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received[5m])",
     "legendFormat": "received"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent[5m])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Clloudwatch CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "RDS CPU",
     "dimensions": { "DBInstanceIdentifier": "$RDS_DATABASE_ID" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Web CPU",
     "dimensions": {
      "AutoScalingGroupName": "ser2019-WebserverAutoScalingGroup-19FX6AAWTLL2X"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Judge CPU",
     "dimensions": {
      "AutoScalingGroupName": "ser2019-JudgehostAutoScalingGroup-1MS4F2BQ0PNQ7"
     },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}