---
- name: restart nginx
  service:
    name: nginx
    enabled: true
    state: restarted

- name: restart PHP FPM
  service:
    name: php{{ php_version.stdout }}-fpm
    enabled: true
    state: restarted
