---
# These tasks configure the DOMjudge judgedaemon with chroot

- name: Create domjudge-run users
  user:
    name: "domjudge-run-{{ item }}"
    createhome: false
    home: /nonexistent
    group: nogroup
    shell: /bin/false
  loop: "{{ cpucore }}"

- name: Create domjudge-run group
  group:
    name: domjudge-run
    state: present

- name: Create temp package directory
  file:
    path: /tmp/dj_ansible
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy chroot DEB packages to install
  synchronize:
    src: install-chroot
    dest: /tmp/dj_ansible/


- name: Copy chroot-list to install
  synchronize:
    src: chroot-list
    dest: /tmp/dj_ansible/



- name: Create chroot
  shell: "set -o pipefail && {{ DJ_DIR }}/misc-tools/dj_make_chroot -y -i openjdk-11-jdk-headless -l \"$(ls /tmp/dj_ansible/install-chroot/*.deb 2>/dev/null | tr '\n' ',')\" -s \"$(ls /tmp/dj_ansible/chroot-list/*.list 2>/dev/null | tr '\n' ',')\" 2>&1 | tee /tmp/dj_make_chroot.log; grep '^Done building chroot in' /tmp/dj_make_chroot.log"
  environment:
    DEBMIRROR: "{%- if WF_RESTRICTED_NETWORK and ICPC_IMAGE -%}https://packages/ubuntu
                {%- elif ICPC_IMAGE -%}https://sysopspackages.icpc.global/ubuntu
                {%- else -%}
                {%- endif -%}"
  args:
    executable: /bin/bash
    creates: "/chroot/domjudge"

- name: Pre-generate the kernel flags for ansible usage
  set_fact:
    procline: "systemd.unified_cgroup_hierarchy=0 cgroup_enable=memory swapaccount=1 isolcpus={{ cpucore | join(',') }}"

- name: Add cgroup kernel parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ procline }}\""

- name: Check cgroup kernel parameters
  command: cat /proc/cmdline
  register: kernel_cmdline
  changed_when: procline not in kernel_cmdline.stdout
  notify:
    - Update grub
    - Reboot

- name: Reboot to activate kernel parameters
  meta: flush_handlers

- name: Copy script to disable turboboost and hyperthreading
  copy:
    src: disable-turboboost_ht
    dest: /usr/local/sbin/
    mode: 0755

- name: Copy tune_cpu systemd unit file
  copy:
    src: tune_cpu.service
    dest: /etc/systemd/system/
    mode: 0644
    group: root
    owner: root
  notify:
    - Enable and restart tune_cpu

- name: Copy judgedaemon related systemd unit files
  copy:
    remote_src: true
    src: "{{ DJ_DIR }}/lib/judge/{{ item }}.service"
    dest: /etc/systemd/system/
    mode: 0644
    group: root
    owner: root
  loop:
    - create-cgroups
    - domjudge-judgedaemon@
  notify:
    - Enable and restart create-cgroups

- name: Template judgedaemon template systemd unit file
  template:
    src: domjudge-judgehost.target.j2
    dest: /etc/systemd/system/domjudge-judgehost.target
    mode: 0644
    group: root
    owner: root
  notify:
    - Enable and restart judgedaemon

- name: Disable systemd timers
  systemd:
    name: "{{ item }}"
    masked: true
  loop:
    - apt-daily-upgrade.timer
    - apt-daily.timer
    - systemd-tmpfiles-clean.timer

- name: Enable and start judgedaemon
  service:
    name: "domjudge-judgehost.target"
    enabled: true
    state: started
    daemon_reload: true
