---
# These tasks configure the DOMjudge judgedaemon with chroot

- name: create domjudge-run users
  user:
    name: domjudge-run-{{ item }}
    createhome: false
    home: /nonexistent
    group: nogroup
    shell: /bin/false
  loop: "{{ cpucore }}"

- name: create domjudge-run group
  group:
    name: domjudge-run
    state: present

- name: create temp package directory
  file:
    path: /tmp/dj_ansible
    state: directory
    owner: root
    group: root
    mode: 0700

- name: copy chroot DEB packages to install
  synchronize:
    src: install-chroot
    dest: /tmp/dj_ansible/

- name: Check if chroot exists
  stat:
    path: /chroot/domjudge
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: chroot_dir

- block:
    - name: create chroot
      shell: "{{ DJ_DIR }}/misc-tools/dj_make_chroot -y -i openjdk-11-jdk-headless -l \"$(ls /tmp/dj_ansible/install-chroot/*.deb 2>/dev/null | tr '\n' ',')\" 2>&1"
      environment:
        DEBMIRROR: "{{ 'https://packages/ubuntu' if WF_RESTRICTED_NETWORK else '' }}"
      register: chroot_creation
      when: not chroot_dir.stat.exists

    - name: store chrootlog in file
      copy:
        content: chroot_creation.stdout
        dest: /tmp/dj_make_chroot.log
        mode: 0644
        owner: domjudge
        group: domjudge

    - name: Remove chroot if we failed
      file:
        state: absent
        path: /chroot/domjudge
      when: "'Done building chroot in' not in chroot_creation.stdout"

    - name: Check if we failed after writing the log
      fail:
        msg: Creation of chroot failed.
      failed_when: "'Done building chroot in' not in chroot_creation.stdout"
  when: not chroot_dir.stat.exists

- name: Pre-generate the kernel flags for ansible usage
  set_fact:
    procline: "cgroup_enable=memory swapaccount=1 systemd.unified_cgroup_hierarchy=0 isolcpus={{ cpucore|join(',') }}"

- name: add cgroup kernel parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"{{ procline }}\""

- name: check cgroup kernel parameters
  command: cat /proc/cmdline
  register: kernel_cmdline
  changed_when: procline not in kernel_cmdline.stdout
  notify:
    - update grub
    - reboot

- name: reboot to activate kernel parameters
  meta: flush_handlers

- name: copy script to disable turboboost and hyperthreading
  copy:
    src: disable-turboboost_ht
    dest: /usr/local/sbin/
    mode: 0755

- name: copy tune_cpu systemd unit file
  copy:
    src: tune_cpu.service
    dest: /etc/systemd/system/
    mode: 0644
    group: root
    owner: root
  notify:
    - enable and restart tune_cpu

- name: copy judgedaemon related systemd unit files
  copy:
    remote_src: true
    src: "{{ DJ_DIR }}/lib/judge/{{ item }}.service"
    dest: /etc/systemd/system/
    mode: 0644
    group: root
    owner: root
  loop:
    - create-cgroups
    - domjudge-judgedaemon@
  notify:
    - enable and restart create-cgroups
    - enable and restart judgedaemon

- name: template judgedaemon template systemd unit file
  template:
    src: domjudge-judgehost.target.j2
    dest: /etc/systemd/system/domjudge-judgehost.target
    mode: 0644
    group: root
    owner: root
  notify:
    - enable and restart judgedaemon

- name: disable systemd timers
  systemd:
    name: "{{ item }}"
    masked: true
  loop:
    - apt-daily-upgrade.timer
    - apt-daily.timer
    - systemd-tmpfiles-clean.timer
