---
# This playbook installs the DOMjudge server(s)

- name: Install master dependency for ipaddr jinja filter
  hosts: localhost
  tasks:
    - name: Install for debian family
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags: install_master,never
      apt:
        state: present
        pkg:
          - python3-netaddr

- name: Setup domserver
  hosts: domserver
  vars:
    host_type: domserver
  become: true
  roles:
    - role: base_packages
      tags: base_packages
    - role: icpc_fixes
      tags: icpc_fixes
      when: ICPC_IMAGE
    - role: system_fixes
      tags: system_fixes
    - role: hosts
      tags: hosts
    - role: ssl
      tags: ssl
      vars:
        INSTALL_SSL_PRIVATE_KEYS: true
    - role: domjudge_user
      tags: domjudge_user
    - role: ssh
      tags: ssh
    - role: mysql_server
      tags: mysql_server
    - role: domjudge_checkout
      tags: domjudge_checkout
    - role: domjudge_build
      tags: domjudge_build
    - role: domserver
      tags: domserver
    - role: mysql_replication
      tags: mysql_replication
      when: REPLICATION_PASSWORD is defined
    - role: keepalived
      tags: keepalived
      when: KEEPALIVED_PRIORITY is defined
    - role: prometheus_target_web
      tags: prometheus_target_web
      vars:
        MARIADB: true
        FPM: true
      when: GRAFANA_MONITORING
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
  handlers:
    - include: handlers.yml
  tasks:
    - name: Install domserver required packages
      apt:
        state: present
        pkg:
          - python3-mysqldb
          - macchanger
          - molly-guard

    - name: Disable developer mode
      lineinfile:
        regexp: '^APP_ENV=dev'
        state: absent
        dest: "{{ DJ_DIR }}/webapp/.env.local"

    - name: Install contest images
      synchronize:
        src: files/domjudge-public/
        dest: "{{ DJ_DIR }}/webapp/public"
        owner: false
        use_ssh_args: true
      notify: Clear application cache

    - name: Grant www-data permisions to image folders
      acl:
        path: "{{ DJ_DIR }}/webapp/public/images/{{ item }}"
        entity: www-data
        etype: user
        permissions: rwx
        state: present
        recursive: true
      loop:
        - teams
        - affiliations
        - banners

    - name: Add documentation in DOMjudge team interface
      copy:
        src: files/docs.yaml
        dest: "{{ DJ_DIR }}/etc/"
        mode: 0644
        group: root
        owner: root
      notify: Clear application cache

    - name: Add autostart shortcuts
      copy:
        src: files/{{ item }}.desktop
        dest: /home/domjudge/.config/autostart/
        owner: domjudge
        group: domjudge
        mode: 0755
      loop:
        - htop
        - taillog-domserver-nginx-error
      when: GRAPHICAL

    - name: Add autostart shortcuts from template
      template:
        src: files/{{ item }}.desktop.j2
        dest: /home/domjudge/.config/autostart/{{ item }}.desktop
        owner: domjudge
        group: domjudge
        mode: 0755
      loop:
        - taillog-domserver-symfony-error
      when: GRAPHICAL
