---
- hosts: domserver
  tasks:
    - name: Disable webserver to stop submissions
      tags: powerloss
      service:
        name: nginx
        state: stopped

- hosts: all
  tasks:
    - name: Disable GDM autologin
      tags: full_lockdown
      lineinfile:
        path: /etc/gdm3/custom.conf
        regexp: 'AutomaticLoginEnable'
        line: 'AutomaticLoginEnable=false'
        create: true
        mode: 0644
      when: GRAPHICAL

- hosts: judgehost
  tasks:
    - name: Disable all running judgedaemons
      tags: full_lockdown
      service:
        name: "{{ item }}"
        state: stopped
      with_sequence: start=0 end={{ ansible_processor_vcpus }} format=domjudge-judgedaemon@%1x

- hosts: domserver:!emergency
  tasks:
    - name: Disable our domserver instance
      # We also disable the startup as we're now in most likely a bad state
      # make sure that replication can only start when someone is looking at it
      tags: full_lockdown
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - nginx
        - php7.4-fpm
        - mysql

- hosts: all:!admin
  tasks:
    - name: Shutdown all non-needed computers
      tags: full_lockdown
      community.general.shutdown:

# Get current running machine
- hosts: localhost

- hosts: all
  tasks:
    - name: Shutdown all machines except for us
      tags: force_lockdown
      community.general.shutdown:
      when: hostvars.localhost.ansible_hostname != ansible_hostname
