# Common definition of handlers
---
- name: clear application cache
  command: "{{ DJ_DIR }}/webapp/bin/console cache:clear"
  become: true
  become_user: domjudge

- name: rebuild domjudge
  become: true
  become_user: domjudge
  make:
    chdir: "{{ DJ_DIR }}"
    target: inplace-install
  notify: fix permissions on domjudge inplace-install

- name: restart nginx
  systemd:
    name: nginx
    enabled: true
    state: restarted

