---
# This playbook installs the DOMjudge judgehosts

- name: Setup judgehost
  hosts: judgehost,online-judgehost
  strategy: free
  vars:
    host_type: judgehost
  become: true
  roles:
    - role: base_packages
      tags: base_packages
    - role: icpc_fixes
      tags: icpc_fixes
      when: ICPC_IMAGE
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
    - role: system_fixes
      tags: system_fixes
    - role: hosts
      tags: hosts
    - role: ssl
      tags: ssl
    - role: domjudge_user
      tags: domjudge_user
    - role: ssh
      tags: ssh
    - role: domjudge_checkout
      tags: domjudge_checkout
    - role: domjudge_build
      tags: domjudge_build
    - role: judgedaemon
      tags: judgedaemon
    - role: domlogo
      tags: domlogo
      when: GRAPHICAL
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
  handlers:
    - import_tasks: handlers.yml
  pre_tasks:
    - name: Check if the service is already available
      stat:
        path: /etc/systemd/system/domjudge-judgedaemon@.service
        get_attributes: false
        get_checksum: false
        get_mime: false
      register: service_file
      check_mode: no
      tags: pretask

    - name: Stop judgedaemon service(s) on every possible core
      service:
        name: "{{ item }}"
        state: stopped
      with_sequence: start=0 end={{ ansible_processor_vcpus }} format=domjudge-judgedaemon@%1x
      when: service_file.stat.exists
      tags: pretask
  tasks:
    - name: Create graphical autostart entries
      when: GRAPHICAL
      block:
        - name: Add autostart shortcuts
          template:
            src: files/rotate.desktop
            dest: /home/domjudge/.config/autostart/
            owner: domjudge
            group: domjudge
            mode: 0755

        - name: Add autostart shortcuts from template
          template:
            src: files/taillog.desktop.j2
            dest: /home/domjudge/.config/autostart/taillog.desktop
            owner: domjudge
            group: domjudge
            mode: 0755
