---
# This playbook installs the DOMjudge judgehosts

- name: Setup judgehost
  hosts: judgehost
  # We always leave 2/3 of the judges online
  serial:
    - 33%
    - 33%
    - 34%
  strategy: free
  vars:
    host_type: judgehost
  become: true
  roles:
    - role: base_packages
      tags: base_packages
    - role: icpc_fixes
      tags: icpc_fixes
      when: ICPC_IMAGE
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
    - role: system_fixes
      tags: system_fixes
    - role: hosts
      tags: hosts
    - role: ssl
      tags: ssl
    - role: domjudge_user
      tags: domjudge_user
    - role: ssh
      tags: ssh
    - role: domjudge_checkout
      tags: domjudge_checkout
    - role: domjudge_build
      tags: domjudge_build
    - role: judgedaemon
      tags: judgedaemon
    - role: domlogo
      tags: domlogo
      when: GRAPHICAL
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
  handlers:
    - include: handlers.yml
  pre_tasks:
    - name: Check if the service is already available
      stat:
        path: /etc/systemd/system/domjudge-judgedaemon@.service
        get_attributes: false
        get_checksum: false
        get_mime: false
      register: service_file
      check_mode: no
      tags: pretask

    - name: Disable all cores
      service:
        name: "{{ item }}"
        state: stopped
      with_sequence: start=0 end={{ ansible_processor_vcpus }} format=domjudge-judgedaemon@%1x
      when: service_file.stat.exists
      tags: pretask
  tasks:
    - name: Add autostart shortcuts
      template:
        src: files/{{ item }}.desktop
        dest: /home/domjudge/.config/autostart/
        owner: domjudge
        group: domjudge
        mode: 0755
      loop:
        - rotate
      when: GRAPHICAL

    - name: Add autostart shortcuts from template
      template:
        src: files/{{ item }}.desktop.j2
        dest: /home/domjudge/.config/autostart/{{ item }}.desktop
        owner: domjudge
        group: domjudge
        mode: 0755
      loop:
        - taillog
      when: GRAPHICAL
