---
# This playbook installs the Management machine

- name: Setup management
  hosts: mgmt
  vars:
    host_type: mgmt
  become: true
  roles:
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
