---
# This playbook installs the presentation admin

- name: Setup presentation admin
  hosts: presadmin
  vars:
    host_type: presadmin
    GRAPHICAL: true
  become: true
  handlers:
    - include: handlers.yml
  roles:
    - role: base_packages
      tags: base_packages
    - role: icpc_fixes
      tags: icpc_fixes
      when: ICPC_IMAGE
    - role: system_fixes
      tags: system_fixes
    - role: hosts
      tags: hosts
    - role: domjudge_user
      tags: domjudge_user
    - role: ssh
      tags: ssh
    - role: presadmin
      tags: presadmin
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
