---
# This playbook installs the presentation client

- name: Setup presentation client
  hosts: presclient
  vars:
    host_type: presclient
    GRAPHICAL: true
  become: true
  handlers:
    - import_tasks: handlers.yml
  roles:
    - role: base_packages
      tags: base_packages
    - role: icpc_fixes
      tags: icpc_fixes
      when: ICPC_IMAGE
    - role: system_fixes
      tags: system_fixes
    - role: hosts
      tags: hosts
    - role: domjudge_user
      tags: domjudge_user
    - role: ssh
      tags: ssh
    - role: presclient
      tags: presclient
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
