---

- hosts: scriptserver
  vars:
    host_type: scriptserver
  become: true
  handlers:
    - include: handlers.yml
  roles:
    - role: base_packages
      tags: base_packages
    - role: icpc_fixes
      tags: icpc_fixes
      when: ICPC_IMAGE
    - role: system_fixes
      tags: system_fixes
    - role: hosts
      tags: hosts
    - role: script_server
      tags: script_server
