---
# These tasks configure SSH stuff

- name: Setup ssh dir for the user
  include: setup_ssh_user.yml
  loop_control:
    loop_var: ssh_user
  loop:
    - user: domjudge
      home: /home/domjudge
    - user: root
      home: /root
