---
# These tasks install keepalived with IP failover

- name: Install keepalived
  apt:
    state: present
    pkg:
      - keepalived

- name: Configure keepalived for domjudge IP failover
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
    group: root
    owner: root
  notify: Restart keepalived service

- name: Start but disable keepalived (so it does not fail back to primary)
  service:
    name: keepalived
    enabled: false
    state: started

- name: Set kernel ARP parameters required by keepalived
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/30-keepalived.conf
    state: present
  loop:
    - { key: "net.ipv4.conf.all.arp_ignore",   value: "1" }
    - { key: "net.ipv4.conf.all.arp_announce", value: "1" }
    - { key: "net.ipv4.conf.all.arp_filter",   value: "0" }
    - { key: "net.ipv4.conf.vrrp/{{ CLUSTER_ID }}.arp_filter",   value: "0" }
    - { key: "net.ipv4.conf.vrrp/{{ CLUSTER_ID }}.accept_local", value: "1" }
    - { key: "net.ipv4.conf.vrrp/{{ CLUSTER_ID }}.rp_filter",    value: "0" }

- name: Install keepalived alert trigger code
  copy:
    src: alerting/
    dest: /home/domjudge/
    owner: domjudge
    group: domjudge
    mode: 0755
