---
# These tasks install keepalived with IP failover

- name: Install keepalived and beep (for alerting)
  apt:
    state: present
    pkg:
      - keepalived
      - beep

- name: Configure keepalived for domjudge IP failover
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
    group: root
    owner: root
  notify: Restart keepalived service

- name: Start but disable keepalived (so it does not fail back to primary)
  service:
    name: keepalived
    enabled: false
    state: started

- name: Install keepalived alert trigger code
  copy:
    src: alerting/
    dest: /home/domjudge/
    owner: domjudge
    group: domjudge
    mode: 0755
