---
# These tasks configure the DOMjudge judgedaemon with chroot

- name: create domjudge-run users
  user: name={{item}} createhome=no home=/nonexistent group=nogroup shell=/bin/false
  with_items:
    - domjudge-run-0
    - domjudge-run-1
    - domjudge-run-2
    - domjudge-run-3

- name: create domjudge-run group
  group: name=domjudge-run state=present

- name: add the restapi secret file
  template:
    src: restapi.secret.j2
    dest: "{{DJ_DIR}}/etc/restapi.secret"
    owner: domjudge
    group: domjudge
    mode: 0600

- name: copy chroot DEB packages to install
  copy:
    src: install-chroot
    dest: /tmp/dj_ansible/

- name: create chroot
  shell: "{{DJ_DIR}}/misc-tools/dj_make_chroot -y -i openjdk-11-jdk-headless -l \"$(ls /tmp/dj_ansible/install-chroot/*.deb 2>/dev/null | tr '\n' ',')\" 2>&1 | tee /tmp/dj_make_chroot.log; grep '^Done building chroot in' /tmp/dj_make_chroot.log"
  environment:
    DEBMIRROR: "{{ 'https://packages/ubuntu' if WF_RESTRICTED_NETWORK else '' }}"
  args:
    creates: "/chroot/domjudge"

- name: add cgroup kernel parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash cgroup_enable=memory swapaccount=1"'
  notify:
    - update grub
    - reboot

- name: copy script to disable turboboost and hyperthreading
  copy:
    src: disable-turboboost_ht
    dest: /usr/local/sbin/
    mode: 0755

- name: copy tune_cpu systemd unit file
  copy:
    src: tune_cpu.service
    dest: /etc/systemd/system/
  notify:
    - restart systemctl
    - enable and restart tune_cpu

- name: copy judgedaemon related systemd unit files
  copy:
    remote_src: true
    src: "{{DJ_DIR}}/lib/judge/{{item}}.service"
    dest: /etc/systemd/system/
  with_items:
    - create-cgroups
    - domjudge-judgehost
  notify:
    - restart systemctl
    - enable and restart create-cgroups
    - enable and restart judgedaemon

- name: reboot to activate kernel parameters and load systemd unit files
  meta: flush_handlers

- name: disable systemd timers
  command: systemctl mask {{item}}
  args:
    creates: /etc/systemd/system/{{item}}
  with_items:
    - apt-daily-upgrade.timer
    - apt-daily.timer
    - systemd-tmpfiles-clean.timer
