---
- name: Restart rsyslog
  service:
    name: rsyslog
    enabled: true
    state: restarted

- name: Restart promtail
  service:
    name: promtail
    enabled: true
    state: restarted
    daemon_reload: true

- name: Restart node-exporter
  service:
    name: prometheus-node-exporter
    enabled: true
    state: restarted
