---
# This task configures packaging and installs various system utilities

- name: World finals fixes for apt sources
  block:
  - name: Replace pc2.ecs.baylor.edu by packages in apt sources
    replace:
      dest: "/etc/apt/{{ item }}"
      regexp: 'sysopspackages\.icpc\.global'
      replace: 'packages'
    loop:
      - sources.list
      - sources.list.d/mono.list
      - sources.list.d/vscode.list
      - sources.list.d/pypy-ubuntu-ppa-buster.list
    notify: Run apt update

  - name: Add packages to hosts file
    lineinfile:
      dest: /etc/hosts
      line: "{{ HOSTS['packages'] }} packages"
    notify: Run apt update

  - name: Remove pycharm repo
    replace:
      dest: /etc/apt/sources.list
      regexp: '^([^#].*pycharm.*)$'
      replace: '# \1'
    notify: Run apt update
  when: ICPC_IMAGE and WF_RESTRICTED_NETWORK

- name: Check for dpkg architecture i386
  command: dpkg --print-foreign-architectures
  register: dpkg_architectures
  changed_when: false
  check_mode: no

- name: Remove unused dpkg architecture i386
  command: dpkg --remove-architecture i386
  notify: Run apt update
  when: dpkg_architectures.stdout.find('i386') != -1

- name: Flush handlers
  meta: flush_handlers

- name: Remove some packages
  apt:
    state: absent
    pkg: "{{ REMOVED_PACKAGES }}"

- name: Install common required/useful packages
  apt:
    state: present
    pkg: "{{ INSTALLED_PACKAGES }}"

- name: Install local DEB packages
  include: install-local-package.yml
  with_fileglob:
    - install-{{ host_type }}/*.deb
