#!/bin/sh -e

printf "checking no_turbo: "
cat /sys/devices/system/cpu/intel_pstate/no_turbo

printf "min perf pct: "
cat /sys/devices/system/cpu/intel_pstate/min_perf_pct

printf "max perf pct: "
cat /sys/devices/system/cpu/intel_pstate/max_perf_pct

echo "scaling governors: "
cat /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor

echo "lscpu: "
lscpu
