#!/bin/sh

if [ -z "$1" ]
then
	echo "Usage dump-db [name]"
	echo ".sql.gz will be appended"
	exit 1
fi

DIR="~/db-dumps/"
mkdir -p $DIR

sudo mysqldump --opt --skip-lock-tables domjudge | pv | gzip -9 > "$DIR/${1}_`date +%FT%T`.sql.gz"
