#!/bin/sh

if [ -z "$1" ]
then
	echo "Usage load-db [name]"
	echo ".sql.gz will be appended"
	exit 1
fi

FILEHOME="/home/domjudge/db-dumps/${1}.sql.gz"
FILEBACKUP="/home/domjudge/db-dumps-backup/${1}.sql.gz"

if [ -f "${FILEHOME}" ]
then
	FILE="${FILEHOME}"
elif [ -f "${FILEBACKUP}" ]
then
	FILE="${FILEBACKUP}"
fi

if [ -z "${FILE++}" ] || [ ! -f "${FILE}" ]
then
	echo "Error. File ${FILE} not found"
	exit 1
fi

pv "${FILE}" | gunzip | sudo mysql domjudge
