# Common tasks before building DOMjudge.
---
- name: add domjudge to hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: 'domserver$'
    line: "{{DOMSERVER_IP}}	domserver"

- include: common_tasks_all.yml

- name: install SSL server certificates
  copy:
    src: "{{ item }}"
    dest: /etc/ssl/certs/
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/ssl/*.crt
  notify: update-ca-certificates

- name: create ca certificates shared directory
  file:
    dest: /usr/local/share/ca-certificates
    state: directory
    owner: root
    group: root

- name: install SSL server certificates into CA certificates
  copy:
    src: "{{ item }}"
    dest: /usr/local/share/ca-certificates
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - files/ssl/*.crt
  notify: update-ca-certificates
