# Common tasks applied to all hosts, including admin ones
---
    - name: set timezone
      timezone:
        name: "{{TIMEZONE}}"

    - include: common_tasks_packages_icpc-wf.yml

    - name: install common required/useful packages
      tags: packages
      apt:
        state: present
        pkg:
        - ack
        - git
        - htop
        - httpie
        - ncdu
        - pv
        - screen
        - autoconf
        - automake
        - efibootmgr
        - curl
        - gcc
        - g++
        - default-jdk-headless
        - make
        - zip
        - unzip
        - php-cli
        - php-gd
        - php-curl
        - php-mysql
        - php-json
        - php-xml
        - php-zip
        - php-mbstring
        - php-intl
        - prometheus-node-exporter
        - bsdmainutils
        - libcgroup-dev
        - libcurl4-gnutls-dev
        - libjsoncpp-dev
        - libmagic-dev
        - composer
        - debootstrap
        - qmlscene
        - texlive-latex-recommended
        - texlive-latex-extra
        - apache2-utils
        - tig
        - bat

    - name: Re-order PXEboot
      shell: efibootmgr -o 2,1

    - name: set PHP timezone for CLI
      lineinfile:
        dest: /etc/php/7.4/cli/php.ini
        state: present
        regexp: 'date\.timezone\s*='
        line: 'date.timezone = {{TIMEZONE}}'

    - name: install local DEB packages
      include: install-local-package.yml
      with_fileglob:
        - files/install-{{host_type}}/*.deb

    - name: configure git as domjudge user
      ini_file:
        dest: /home/domjudge/.gitconfig
        section: user
        option: "{{item.name}}"
        value: "{{item.value}}"
        owner: domjudge
        group: domjudge
      with_items:
        - { name: 'email', value: 'team@domjudge.org' }
        - { name: 'name', value: 'DOMjudge team' }

    - name: configure git to rebase on pull
      ini_file:
        dest: /home/domjudge/.gitconfig
        section: branch
        option: "autosetuprebase"
        value: "remote"
        owner: domjudge
        group: domjudge

    - name: Create .ssh directory
      file: path="/home/domjudge/.ssh" group=domjudge owner=domjudge mode=0700 state=directory

    - name: Copy SSH key for git access
      copy:
        content: "{{DJ_GIT_SSH_KEY}}"
        dest: /home/domjudge/.ssh/dj_git_ssh_key
        owner: domjudge
        group: domjudge
        mode: 0600
      when: DJ_GIT_SSH_KEY is defined

    - name: Create SSH config
      template: src=files/ssh-config-domjudge.j2 dest=/home/domjudge/.ssh/config owner=domjudge group=domjudge mode=0600
      when: DJ_GIT_HOST is defined

    - name: add all hosts to hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: '{{ item }}$'
        line: "{{ hostvars[item].ansible_host }}	{{ item }}"
      loop: "{{ groups['all'] }}"

    - name: add domjudge in hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: 'domserver'
        line: "{{DOMSERVER_IP}}	domjudge domserver"

    - name: configure domjudge logging
      copy: src=files/rsyslog.domjudge.conf dest=/etc/rsyslog.d/domjudge.conf
      notify: restart rsyslog

    - name: configure domjudge logrotate
      copy: src=files/logrotate.domjudge dest=/etc/logrotate.d/domjudge

    - name: Force enable alt-tab for switching windows
      copy: src=files/dconf/ dest=/etc/dconf/

    - name: Update dconf configuration for alt-tab window switching
      shell: dconf update
