# Common tasks applied to all hosts, including admin ones
---
- name: add NTP servers
  lineinfile:
    dest: /etc/systemd/timesyncd.conf
    regexp: '^#?NTP='
    line: "NTP=10.3.3.208 10.3.3.209"
  when: WF_RESTRICTED_NETWORK

- name: remove source line from interfaces
  lineinfile:
    dest: /etc/network/interfaces
    regexp: '^source-'
    state: absent

- name: restart systemd timesyncd
  command: systemctl restart systemd-timesyncd

- name: Re-order PXEboot
  shell: efibootmgr -o {{ EFI_ORDER }}
  when: EFI_ORDER is defined

- name: set timezone
  timezone:
    name: "{{TIMEZONE}}"

- name: set PHP timezone for CLI
  lineinfile:
    dest: /etc/php/7.4/cli/php.ini
    state: present
    regexp: 'date\.timezone\s*='
    line: 'date.timezone = {{TIMEZONE}}'

- name: install local DEB packages
  include: install-local-package.yml
  with_fileglob:
    - files/install-{{host_type}}/*.deb

- name: add all hosts to hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ item }}$'
    line: "{{ hostvars[item].ansible_host }}	{{ item }}"
  loop: "{{ groups['all'] }}"

- name: add domjudge in hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: 'domserver'
    line: "{{DOMSERVER_IP}}	domjudge domserver"

- name: enable bash completion globally
  blockinfile:
    path: /etc/bash.bashrc
    insertafter: "# enable bash completion in interactive shells"
    block: |
      if ! shopt -oq posix; then
        if [ -f /usr/share/bash-completion/bash_completion ]; then
          . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
          . /etc/bash_completion
        fi
      fi

- name: configure domjudge logging
  copy: src=files/rsyslog.domjudge.conf dest=/etc/rsyslog.d/domjudge.conf
  notify: restart rsyslog

- name: configure domjudge logrotate
  copy: src=files/logrotate.domjudge dest=/etc/logrotate.d/domjudge

- name: Force enable alt-tab for switching windows
  copy: src=files/dconf/ dest=/etc/dconf/
  notify: update dconf

- name: disable mumble,selfie services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - mumble-server
    - selfie
