# Common tasks before building DOMjudge.
---
    - name: add domjudge to hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: '^10\.3\.3\.215'
        line: "10.3.3.215	domjudge"

    - name: set timezone
      timezone:
        name: "{{TIMEZONE}}"

    - include: common_tasks_packages_icpc-wf.yml

    - name: install common required/useful packages
      tags: packages
      apt: pkg={{item}} state=present
      with_items:
        - autoconf
        - automake
        - collectd-core
        - curl
        - git
        - gcc
        - g++
        - default-jdk-headless
        - make
        - zip
        - unzip
        - php
        - php-cli
        - php-gd
        - php-curl
        - php-mysql
        - php-json
        - php-xml
        - php-zip
        - php-mbstring
        - bsdmainutils
        - libcgroup-dev
        - libcurl4-gnutls-dev
        - libjsoncpp-dev
        - libmagic-dev
        - composer
        - debootstrap
        - ack-grep
        - htop
        - ncdu
        - httpie
        - mycli
        - screen
        - qmlscene

    - name: create domjudge user
      user:
        name: domjudge
        shell: /bin/bash
        groups: sudo
        password: "{{DJ_SHELL_USER_PW | default(omit)}}"

    - name: Add authorized key
      authorized_key:
        user: domjudge
        state: present
        key: "{{DJ_SSH_KEY}}"

    - name: configure git as domjudge user
      become: yes
      become_user: domjudge
      #command: git config --global {{item.name}} "{{item.value}}"
      ini_file: dest=/home/domjudge/.gitconfig section=user option="{{item.name}}" value="{{item.value}}"
      with_items:
        - { name: 'email', value: 'team@domjudge.org' }
        - { name: 'name', value: 'DOMjudge team' }

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'

    - name: Create .ssh directory
      file: path="/home/domjudge/.ssh" group=domjudge owner=domjudge mode=0700 state=directory

    - name: Copy SSH key for git access
      copy: src=files/dj_ed25519 dest=/home/domjudge/.ssh/dj_ed25519 owner=domjudge group=domjudge mode=0600

    - name: Create SSH config
      template: src=files/ssh-config-domjudge.j2 dest=/home/domjudge/.ssh/config owner=domjudge group=domjudge mode=0600

    - name: create working copy from the repo
      become: yes
      become_user: domjudge
      git: repo=domjudge@{{DJ_GIT_HOST}}:domjudge dest={{DJ_DIR}} version={{DJ_BRANCH}} accept_hostkey=yes update=yes
      register: git_working_copy

    - name: Check composer dependencies present
      local_action: stat path=files/lib/vendor
      register: libvendor

    - name: Copy in composer dependencies (if they exist locally)
      become: no
      tags: sync
      synchronize:
        src: files/lib/vendor/
        dest: "{{DJ_DIR}}/lib/vendor/"
        owner: no
        use_ssh_args: true
        rsync_path: sudo rsync
      when: libvendor.stat.exists

    - name: copy collectd configuration
      template: src=files/collectd.conf.j2 dest=/etc/collectd/collectd.conf
      notify: restart collectd
      when: COLLECTD_MYSQL_PASSWORD is defined

    - name: create directory for collectd mysql modules
      file: path=/etc/collectd/collectd-python state=directory mode=0755
      when:
        - COLLECTD_MYSQL_PASSWORD is defined
        - "'domjudge-primary' in ansible_hostname or 'domjudge-backup' in ansible_hostname"

    - name: copy mysql metrics collection script
      copy: src=files/collectd-mysql.py dest=/etc/collectd/collectd-python/mysql.py mode=0755
      when:
        - COLLECTD_MYSQL_PASSWORD is defined
        - "'domjudge-primary' in ansible_hostname or 'domjudge-backup' in ansible_hostname"

    - name: configure domjudge logging
      copy: src=files/rsyslog.domjudge.conf dest=/etc/rsyslog.d/domjudge.conf
      notify: restart rsyslog

    - name: configure domjudge logrotate
      copy: src=files/logrotate.domjudge dest=/etc/logrotate.d/domjudge

    - name: copy DOMjudge logo binary
      copy: src=files/domlogo dest=/home/domjudge/domlogo owner=domjudge group=domjudge mode=0755

    - name: make sure lightdm config directory exists
      file: path=/etc/lightdm/lightdm.conf.d state=directory

    - name: autologin domjudge user
      copy: src=files/lightdm-domjudge.conf dest=/etc/lightdm/lightdm.conf.d/domjudge.conf

    - name: make sure autostart directory exists
      file: dest=/home/domjudge/.config/autostart state=directory owner=domjudge group=domjudge
      tags: fix_autostart
