# Common tasks to build DOMjudge.
---
    - name: run maintainer-conf
      become: yes
      become_user: domjudge
      command: make maintainer-conf CONFIGURE_FLAGS='--disable-doc-build --with-judgehost_chrootdir=/chroot/domjudge-systest'
      register: dj_configured
      args:
        chdir: "{{DJ_DIR}}"
        creates: "{{DJ_DIR}}/paths.mk"

    - name: check if domjudge is built
      stat: path="{{DJ_DIR}}/judge/judgedaemon"
      register: judgedaemon_binary

    - name: build domjudge
      become: yes
      become_user: domjudge
      shell: make maintainer-install chdir={{DJ_DIR}}
      when: git_working_copy.changed or dj_configured.changed or not judgedaemon_binary.stat.exists

    - name: fix permissions on things
      shell: make -C {{DJ_DIR}} maintainer-postinstall-permissions

    - name: copy domjudge-sudoers file
      copy: remote_src=True src={{DJ_DIR}}/etc/sudoers-domjudge dest=/etc/sudoers.d/domjudge-systest mode=0440 owner=root group=root

