# Common tasks applied to all hosts, including admin ones
---
- name: install local DEB packages
  include: install-local-package.yml
  with_fileglob:
    - files/install-{{host_type}}/*.deb

- name: add all hosts to hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ item }}$'
    line: "{{ hostvars[item].ansible_host }}	{{ item }}"
  loop: "{{ groups['all'] }}"

- name: add domjudge in hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: 'domserver'
    line: "{{DOMSERVER_IP}}	domjudge domserver"

- name: configure domjudge logging
  copy: src=files/rsyslog.domjudge.conf dest=/etc/rsyslog.d/domjudge.conf
  notify: restart rsyslog

- name: configure domjudge logrotate
  copy: src=files/logrotate.domjudge dest=/etc/logrotate.d/domjudge
