# Common packaging stuff during ICPC World Finals.
---
    - name: replace pc2.ecs.baylor.edu by packages in apt sources
      tags: packages
      replace:
        dest: "/etc/apt/{{ item }}"
        regexp: 'pc2\.ecs\.baylor\.edu'
        replace: 'packages'
      with_items:
        - sources.list
        - sources.list.d/microsoft.list
        - sources.list.d/mono.list
        - sources.list.d/vscode.list
        - sources.list.d/pypy-ubuntu-ppa-buster.list

    - name: remove unused dpkg architecture i386
      tags: packages
      command: dpkg --remove-architecture i386

    - name: run apt update
      tags: packages
      command: apt update

    - name: remove pycharm repo
      tags: packages
      replace:
        dest: /etc/apt/sources.list
        regexp: '^([^#].*pycharm.*)$'
        replace: '# \1'

    - name: add packages to hosts file
      tags: packages
      lineinfile:
        dest: /etc/hosts
        regexp: '^10\.3\.3\.209'
        line: "10.3.3.209	packages"

    - name: remove some packages
      tags: packages
      apt:
        pkg: ntp
        state: absent

    - meta: flush_handlers
      tags: packages

    - name: add NTP servers
      tags: packages
      lineinfile:
        dest: /etc/systemd/timesyncd.conf
        regexp: '^#?NTP='
        line: "NTP=10.3.3.208 10.3.3.209"

    - name: remove source line from interfaces
      tags: packages
      lineinfile:
        dest: /etc/network/interfaces
        regexp: '^source-'
        state: absent

    - name: restart systemd timesyncd
      command: systemctl restart systemd-timesyncd
