---

- name: setup domserver
  hosts: all
  tasks:
    - name: give domjudge a decent shell
      user: name=domjudge shell=/bin/bash
    - name: copy root public key to domjudge user
      authorized_key:
        user: domjudge
        state: present
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJWz3OEhwRBxO9+Sc0EJHRu0Y/gGy6H9Xd3s4x6WZ941 root@domjudge-ccsadmin1
    - name: copy domjudge public key to domjudge user
      authorized_key:
        user: domjudge
        state: present
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPsTOPgh8QYBudu7IOLETq4ek13RBB+pM/spOboCK1wO domjudge@domjudge-ccsadmin1

