---
# This playbook installs the DOMjudge judgehosts

- name: setup judgehost
  hosts: judgehost
  serial:
    - 33% # We always leave 1/3 of the judges online
    - 33%
    - 34%
  vars:
    host_type: judgehost
  become: yes
  roles:
    - role: base_packages
      tags: base_packages
    - role: icpc_fixes
      tags: icpc_fixes
      when: ICPC_IMAGE
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
    - role: system_fixes
      tags: system_fixes
    - role: hosts
      tags: hosts
    - role: ssl
      tags: ssl
    - role: domjudge_user
      tags: domjudge_user
    - role: domjudge_checkout
      tags: domjudge_checkout
    - role: domjudge_build
      tags: domjudge_build
    - role: judgedaemon
      tags: judgedaemon
    - role: ssh
      tags: ssh
    - role: domlogo
      tags: domlogo
    - role: prometheus_target_all
      tags: prometheus_target_all
      when: GRAFANA_MONITORING
  pre_tasks:
    - name: Get current services
      service_facts:
    - name: Disable all cores
      service:
        name="domjudge-judgedaemon@{{item}}"
        state=stopped
      with_sequence: start=0 end={{ ansible_processor_vcpus }} format=domjudge-judgedaemon@%1x
      when: '"domjudge-judgedaemon@0.service" in services'
  tasks:
    - name: add autostart shortcuts
      template:
        src: files/{{item}}.desktop
        dest: /home/domjudge/.config/autostart/
        owner: domjudge
        group: domjudge
        mode: 0755
      loop:
        - rotate

    - name: add autostart shortcuts from template
      template:
        src: files/{{item}}.desktop.j2
        dest: /home/domjudge/.config/autostart/{{item}}.desktop
        owner: domjudge
        group: domjudge
        mode: 0755
      loop:
        - taillog
