---
# This playbook installs the DOMjudge judgehosts

- name: setup judgehost
  hosts: judgehost
  vars:
    host_type: judgehost
  become: yes
  roles:
    - role: base_packages
      tags: base_packages
    - role: system_fixes
      tags: system_fixes
    - role: ssl
      tags: ssl
    - role: domjudge_user
      tags: domjudge_user
    - role: domjudge_checkout
      tags: domjudge_checkout
    - role: domjudge_build
      tags: domjudge_build
    - role: judgedaemon
      tags: judgedaemon
    - role: ssh
      tags: ssh
    - role: domlogo
      tags: domlogo
  pre_tasks:
    - pause:
        prompt: "Did you disable all judges"
      delegate_to: localhost
  tasks:

    - include: common_tasks_all.yml

    - name: add autostart shortcuts
      copy: src=files/{{item}}.desktop dest=/home/domjudge/.config/autostart/ owner=domjudge group=domjudge mode=0755
      with_items:
        - taillog
        - rotate
