---

- name: setup judgehost
  hosts: judgehost
  become: yes
  handlers:
    - name: update-grub
      command: update-grub
    - name: update-ca-certificates
      command: update-ca-certificates
    - name: restart collectd
      service: name=collectd state=restarted
    - name: restart rsyslog
      service: name=rsyslog enabled=yes state=restarted
    - name: restart systemctl
      shell: systemctl daemon-reload
  tasks:
    - name: include global variables
      include_vars: variables.yml

    - name: create domjudge-run users
      user: name={{item}} createhome=no home=/nonexistent group=nogroup shell=/bin/false
      with_items:
        - domjudge-run-0
        - domjudge-run-1
        - domjudge-run-2
        - domjudge-run-3
    - name: create domjudge-run group
      group: name=domjudge-run state=present

    - include: common_tasks_prebuild.yml

    - name: copy DEB packages to install
      copy: src=files/install-{{item}} dest=/tmp/dj_ansible/
      with_items:
        - judgehost
        - chroot
      register: local_deb_packages

    - name: install local DEB packages
      shell: "dpkg -i /tmp/dj_ansible/install-judgehost/*.deb"
      when: local_deb_packages.changed

    - name: template out the restapi secret file
      template: src=files/restapi.secret.j2 dest={{DJ_DIR}}/etc/restapi.secret owner=domjudge group=domjudge mode=0600

    - name: disable clearing Symfony cache when building
      lineinfile:
        dest: "{{DJ_DIR}}/Makefile"
        regexp: "^(.*-C webapp clear-cache)$"
        line: '#\1'
        backrefs: yes

    - include: common_tasks_build.yml

    - name: re-enable clearing Symfony cache when building
      lineinfile:
        dest: "{{DJ_DIR}}/Makefile"
        regexp: "^#(.*-C webapp clear-cache)$"
        line: '\1'
        backrefs: yes

    - name: enable internal monitor
      file: path=/usr/share/X11/xorg.conf.d/22-icpc.conf state=absent

    - name: create chroot
      shell: "{{DJ_DIR}}/misc-tools/dj_make_chroot -y -l \"$(ls /tmp/dj_ansible/install-chroot/*.deb 2>/dev/null | tr '\n' ',')\" 2>&1 | tee /tmp/dj_make_chroot.log"
      args:
        creates: "/chroot/domjudge"

    - name: fix kernel parameters
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash cgroup_enable=memory swapaccount=1"'
      notify: update-grub

    - name: copy script to disable turboboost and hyperthreading
      copy: src=files/disable-turboboost_ht dest=/usr/local/sbin/ mode=0755

    - name: copy systemd unit files
      copy: src=files/{{item}}.service dest=/etc/systemd/system/
      tags: updateservice
      with_items:
        - create_cgroups
        - tune_cpu
        - judgedaemon
      notify: restart systemctl

    - name: make sure systemctl is restarted
      meta: flush_handlers

    - name: enable and restart the services we just copied
      service: name={{item}} enabled=yes state=restarted
      with_items:
        - create_cgroups
        - tune_cpu
        - judgedaemon

    - name: add autostart shortcuts
      copy: src=files/{{item}}.desktop dest=/home/domjudge/.config/autostart/ owner=domjudge group=domjudge mode=0755
      with_items:
        - taillog
        - rotate
        - domjudgelogo

    - name: disable systemd timers
      command: systemctl mask {{item}}
      args:
        creates: /etc/systemd/system/{{item}}
      with_items:
        - apt-daily-upgrade.timer
        - apt-daily.timer
        - systemd-tmpfiles-clean.timer
