---

- name: setup judgehost
  hosts: judgehost
  vars:
    host_type: judgehost
  become: yes
  handlers:
    - name: update-grub
      command: update-grub
    - name: update-ca-certificates
      command: update-ca-certificates
    - name: restart collectd
      service: name=collectd state=restarted
    - name: restart rsyslog
      service: name=rsyslog enabled=yes state=restarted
    - name: restart systemctl
      shell: systemctl daemon-reload
  tasks:
    - name: include global variables
      include_vars: variables.yml

    - name: create domjudge-run users
      user: name={{item}} createhome=no home=/nonexistent group=nogroup shell=/bin/false
      with_items:
        - domjudge-run-0
        - domjudge-run-1
        - domjudge-run-2
        - domjudge-run-3
        - domjudge-run-4
        - domjudge-run-5
    - name: create domjudge-run group
      group: name=domjudge-run state=present

    - include: common_tasks_prebuild.yml

    - name: template out the restapi secret file
      template: src=files/restapi.secret.j2 dest={{DJ_DIR}}/etc/restapi.secret owner=domjudge group=domjudge mode=0600

    - name: disable clearing Symfony cache when building
      lineinfile:
        dest: "{{DJ_DIR}}/Makefile"
        regexp: "^(.*-C webapp clear-cache)$"
        line: '#\1'
        backrefs: yes

    - include: common_tasks_build.yml

    - name: re-enable clearing Symfony cache when building
      lineinfile:
        dest: "{{DJ_DIR}}/Makefile"
        regexp: "^#(.*-C webapp clear-cache)$"
        line: '\1'
        backrefs: yes

    - name: enable internal monitor
      file: path=/usr/share/X11/xorg.conf.d/22-icpc.conf state=absent

    - name: remove apt-transport-https from bionic debootstrap file
      lineinfile:
        path: /usr/share/debootstrap/scripts/bionic
        regexp: 'ca-certificates'
        line: '                base="$base ca-certificates"'

    - name: copy chroot DEB packages to install
      copy: src=files/install-chroot dest=/tmp/dj_ansible/

    - name: create chroot
      shell: "{{DJ_DIR}}/misc-tools/dj_make_chroot -y -i openjdk-11-jdk-headless -l \"$(ls /tmp/dj_ansible/install-chroot/*.deb 2>/dev/null | tr '\n' ',')\" 2>&1 | tee /tmp/dj_make_chroot.log"
      environment:
        DEBMIRROR: https://pc2cancer.ecs.csus.edu/ubuntu
      args:
        creates: "/chroot/domjudge-systest"

    - name: fix kernel parameters
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash cgroup_enable=memory swapaccount=1"'
      notify: update-grub

    - name: copy systemd unit files
      copy: src=files/{{item}}.service dest=/etc/systemd/system/
      tags: updateservice
      with_items:
        - create_cgroups
        - judgedaemon0
        - judgedaemon1
        - judgedaemon2
        - judgedaemon3
        - judgedaemon4
        - judgedaemon5
      notify: restart systemctl

    - name: make sure systemctl is restarted
      meta: flush_handlers

    - name: enable and restart the services we just copied
      service: name={{item}} enabled=yes state=restarted
      with_items:
        - create_cgroups
        - judgedaemon0
        - judgedaemon1
        - judgedaemon2
        - judgedaemon3
        - judgedaemon4
        - judgedaemon5
