---

- name: setup judgehost
  hosts: judgehost
  become: yes
  handlers:
    - name: update-grub
      command: update-grub
    - name: update-ca-certificates
      command: update-ca-certificates
    - name: restart collectd
      service: name=collectd state=restarted
  tasks:
    - name: include global variables
      include_vars: variables.yml

    - name: create domjudge-run users
      user: name={{item}} createhome=no home=/nonexistent group=nogroup shell=/bin/false
      with_items:
        - domjudge-run-0
        - domjudge-run-1
        - domjudge-run-2
        - domjudge-run-3
    - name: create domjudge-run group
      group: name=domjudge-run state=present

    - include: common_tasks_prebuild.yml

    - name: template out the restapi secret file
      template: src=files/restapi.secret.j2 dest={{DJDIR}}/etc/restapi.secret owner=domjudge group=domjudge mode=0600

    - name: install server certificate
      copy: src=files/domserver.crt dest=/usr/local/share/ca-certificates/domserver.crt
      notify: update-ca-certificates

    - include: common_tasks_build.yml

    - name: enable internal monitor
      file: path=/usr/share/X11/xorg.conf.d/22-icpc.conf state=absent

    - name: create chroot
      shell: "DEBMIRROR='https://packages/ubuntu' {{DJDIR}}/misc-tools/dj_make_chroot -y -i icpc-kotlinc 2>&1 | tee /tmp/dj_make_chroot.log"
      args:
        creates: "/chroot/domjudge"

    - name: fix kernel parameters
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash cgroup_enable=memory swapaccount=1"'
      notify: update-grub

    - name: copy systemd unit files
      copy: src=files/{{item}}.service dest=/etc/systemd/system/
      tags: updateservice
      with_items:
        - create_cgroups
        - tune_cpu
        - judgedaemon

    - name: enable and restart the services we just copied
      service: name={{item}} enabled=yes state=restarted
      with_items:
        - create_cgroups
        - tune_cpu
        - judgedaemon

    - name: autologin domjudge user
      copy: src=files/lightdm-domjudge.conf dest=/etc/lightdm/lightdm.conf.d/domjudge.conf

    - name: make sure autostart directory exists
      file: dest=/home/domjudge/.config/autostart state=directory owner=domjudge group=domjudge
      tags: fix_autostart

    - name: add autostart shortcuts
      copy: src=files/{{item}}.desktop dest=/home/domjudge/.config/autostart/ owner=domjudge group=domjudge mode=0755
      with_items:
        - taillog
        - rotate
        - domjudgelogo

    - name: disable systemd timers
      command: systemctl mask {{item}}
      args:
        creates: /etc/systemd/system/{{item}}
      with_items:
        - apt-daily-upgrade.timer
        - apt-daily.timer
        - systemd-tmpfiles-clean.timer
