---

- name: setup judgehost
  hosts: judgehost
  become: yes
  handlers:
    - name: update-grub
      command: update-grub
    - name: update-ca-certificates
      command: update-ca-certificates
  tasks:
    - name: include global variables
      include_vars: variables.yml

    - name: create domjudge user
      user:
        name: domjudge
        password: "{{DOMJUDGE_USER_PASS}}"

    - name: create domjudge-run users
      user: name={{item}} createhome=no home=/nonexistent group=nogroup shell=/bin/false
      with_items:
        - domjudge-run-0
        - domjudge-run-1
        - domjudge-run-2
        - domjudge-run-3
    - name: create domjudge-run group
      group: name=domjudge-run state=present

    - name: sync domjudge git repo from this workstation to the host
      register: create_bare_repo
      become: no
      synchronize:
        src: files/domjudge-bare.git/
        dest: /home/domjudge/domjudge-bare.git
        use_ssh_args: true
        rsync_path: sudo rsync

    - include: common_tasks_prebuild.yml

    - name: template out the restapi secret file
      template: src=files/restapi.secret.j2 dest={{DJDIR}}/etc/restapi.secret owner=domjudge group=domjudge mode=0600

    - name: add domserver to hosts file
      tags: domserver
      lineinfile:
        dest: /etc/hosts
        regexp: '^.*domserver$'
        line: "{{DOMSERVER_IP}}	domserver"
    - name: install server certificate
      copy: src=files/domserver.crt dest=/usr/local/share/ca-certificates/domserver.crt
      notify: update-ca-certificates

    - include: common_tasks_build.yml

    - name: create chroot
      shell: "{{DJDIR}}/misc-tools/dj_make_chroot -y -i icpc-kotlinc"
      args:
        creates: "/chroot/domjudge"

    - name: fix kernel parameters
      lineinfile:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash cgroup_enable=memory swapaccount=1"'
      notify: update-grub

    - name: copy script to disable turboboost etc.
      copy: src=files/disable-turboboost_ht dest={{DJDIR}}/bin/ mode=0755

    - name: copy systemd unit files
      copy: src=files/{{item}}.service dest=/etc/systemd/system/
      tags: updateservice
      with_items:
        - create_cgroups
        - tune_cpu
        - judgedaemon

    - name: enable and restart the services we just copied
      service: name={{item}} enabled=yes state=restarted
      with_items:
        - create_cgroups
        - tune_cpu
        - judgedaemon

    - name: make sure autostart directory exists
      file: dest=/home/domjudge/.config/autostart state=directory owner=domjudge group=domjudge
      tags: fix_autostart

    - name: add autostart shortcuts
      copy: src=files/{{item}}.desktop dest=/home/domjudge/.config/autostart/ owner=domjudge group=domjudge mode=0755
      with_items:
        - taillog
        - rotate
