---
- name: Restart cds
  systemd:
    name: cds
    enabled: true
    state: restarted
    daemon_reload: true

- name: Restart nginx
  systemd:
    name: nginx
    enabled: true
    state: restarted
