---
# Define here handlers associated to this role.

- name: restart systemctl
  shell: systemctl daemon-reload

- name: enable and restart tune_cpu
  service: name=tune_cpu enabled=yes state=restarted

- name: enable and restart create-cgroups
  service: name=create-cgroups enabled=yes state=restarted

- name: enable and restart judgedaemon
  service:
    name="domjudge-judgedaemon@{{item}}"
    enabled=yes
    state=restarted
  with_items: "{{CPUCORE}}"

- name: update grub
  shell: update-grub

- name: reboot
  reboot:
