---
- name: Install script-server dependencies
  apt:
    name:
      - python3-tornado
      - apache2-utils # for htpasswd auth
    state: present

- name: Create directory for script-server to live
  file:
    path: /opt/script-server
    mode: "0755"
    owner: root
    group: root
    state: directory

- name: Install script-server
  when: ICPC_IMAGE
  unarchive:
    src: "script-server.zip"
    dest: /opt/script-server
    remote_src: false
    creates: /opt/script-server/launcher.py

- name: Install script-server
  when: not ICPC_IMAGE
  unarchive:
    src: "https://github.com/bugy/script-server/releases/download/1.18.0/script-server.zip"
    dest: /opt/script-server
    remote_src: true
    creates: /opt/script-server/launcher.py

- name: Configure the server
  template:
    src: conf.json.j2
    dest: /opt/script-server/conf/conf.json
    mode: "0644"
    owner: root
    group: root

- name: Create systemd service for script-server
  notify: Restart script-server
  copy:
    mode: "0644"
    dest: /etc/systemd/system/script-server.service
    content: |
      [Unit]
      Description=Script Server
      After=network.target
      StartLimitIntervalSec=0

      [Service]
      Type=simple
      Restart=always
      RestartSec=1
      ExecStart=/usr/bin/python3 /opt/script-server/launcher.py

      [Install]
      WantedBy=multi-user.target

- name: Ensure required directories exist
  file:
    state: directory
    mode: "0755"
    path: /opt/script-server/conf/{{ item }}
  loop:
    - scripts
    - runners

- name: Create scripts
  copy:
    content: "{{ item.content }}"
    dest: /opt/script-server/conf/scripts/{{ item.name }}
    mode: "0755"
  with_items: "{{ script_server_commands }}"

- name: Create script config definitions
  ansible.builtin.template:
    src: command_template.yml.j2
    dest: /opt/script-server/conf/runners/{{ item.name }}.yaml
    mode: "0644"
  with_items: "{{ script_server_commands }}"

- name: Start + enable script-server
  service:
    name: script-server
    state: started
    enabled: true

