---
# These tasks configure metric collectors

- name: Every webserver runs nginx so expose metrics
  apt:
    state: present
    pkg:
      - prometheus-nginx-exporter
  notify: Restart nginx-exporter

- name: Expose MariaDB metrics
  when: MARIADB
  apt:
    state: present
    pkg:
      - prometheus-mysqld-exporter
  notify: Restart mysqld-exporter

- name: Scrape mysql exporter with TLS encryption
  lineinfile:
    dest: /etc/default/prometheus-mysqld-exporter
    state: present
    regexp: '^ARGS=""'
    line: 'ARGS="--web.config.file /etc/prometheus/prometheus-authentication.yml"'
  notify: Restart mysqld-exporter

# Gather PHP-FPM statistics
# The exporter from this is currently not in deb sources
# so we need to download this from GitHub see the README in files
- name: Install PHP-fpm exporter binary
  when: FPM and not WF_RESTRICTED_NETWORK
  ansible.builtin.unarchive:
    src: https://github.com/hipages/php-fpm_exporter/releases/download/v2.0.4/php-fpm_exporter_2.0.4_linux_amd64.tar.gz
    dest: /usr/bin/
    remote_src: true
    exclude:
      - LICENSE
      - README.md
  notify: Restart php-exporter

- name: Install PHP-fpm exporter binary (local cache)
  when: FPM and WF_RESTRICTED_NETWORK
  block:
    - name: Copy local php-fpm deb to monitoring host
      copy:
        src: php-fpm.tar.gz
        dest: /srv/php-fpm.tar.gz

    - name: Install local archive on remote
      ansible.builtin.unarchive:
        src: /srv/php-fpm.tar.gz
        dest: /usr/bin/
        remote_src: true
        exclude:
          - LICENSE
          - README.md
      notify: Restart php-exporter

- name: Export PHP-FPM metrics
  when: FPM
  synchronize:
    src: php-fpm-exporter.service
    dest: /etc/systemd/system/php-fpm-exporter.service
  notify: Restart php-exporter

# Gather NGINX statistics,
# Observe that we use the observed process itself in the monitoring
- name: Get NGINX status
  template:
    src: nginx-status.conf.j2
    dest: /etc/nginx/sites-enabled/nginx-status.conf
    mode: 0644
  notify: Restart nginx

# In the future add: --web.config /etc/prometheus/prometheus-authentication.yml"'
# see: https://github.com/nginxinc/nginx-prometheus-exporter
# The version at the WFLuxor in the repository is not new enough
- name: Prometheus nginx exporter
  lineinfile:
    dest: /etc/default/prometheus-nginx-exporter
    state: present
    regexp: '^ARGS=""'
    line: 'ARGS="-web.listen-address=127.0.0.1:19113 -nginx.scrape-uri=http://localhost:8787/basic_status"'
  notify: Restart nginx-exporter

- name: Create storage dir for exporter settings
  when: MARIADB
  file:
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0700
    path: /var/lib/prometheus

# Because the scrape happens inside the same machine we reuse the DB password
# which is also used for the normal installation
- name: Create MySQL authentication file
  when: MARIADB
  template:
    src: mysqld-exporter-authentication.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
    owner: prometheus
    mode: 0644
  notify: Restart mysqld-exporter
