---
# These tasks add entries to /etc/hosts

- name: Set the hostname based on inventory
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set new hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    group: root
    owner: root
    mode: 0644
