name: Test contest deployment (ansible scripts)

on: [push,pull_request]

jobs:
  test_domjudge_role:
    strategy:
      #matrix:
      #  os: [ubuntu-latest, ubuntu-20.04]
      #  role: [domserver,judgehost]
      matrix:
        os: [ubuntu-latest]
        role: [domserver]
    runs-on: ${{ matrix.os }}
    container: ubuntu
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: remove package
        run: apt update; apt purge mysql-server -y
      - name: Install ansible lint tools + SQL server
        run: apt install ansible sudo -y
      - run: apt install mariadb-server -y
      - name: Check that mariadb works
        run: service mariadb restart || true
      - name: Check that mariadb works
        run: sudo systemctl status mariadb.service || true
      - name: Check that mariadb works
        run: sudo systemctl status mariadb.service || true
      - run: cat /var/log/syslog
      - run: ls -atrl /var/log/mysql
      - name: Fix service
        run: cp icpc-wf/ansible/mysqlhandler.yml icpc-wf/ansible/roles/mysql_server/handlers/main.yml
      - name: Setup the hosts file
        working-directory: ./icpc-wf/ansible
        run: sed -i 's/\[${{ matrix.role }}\]/[removed]/g' hosts; printf '\n[${{ matrix.role }}]\ngithub-action\tansible_host=localhost ansible_connection=local' >> hosts
      - name: Generate insecure credentials
        working-directory: ./icpc-wf/ansible
        run: mv group_vars/all/secret.yml{.example,}
      - name: Run the default deployment method
        working-directory: ./icpc-wf/ansible
        run: make ${{ matrix.role }}
