#!/bin/bash -e

shopt -s extglob

declare -A core_ids

for cpu in /sys/devices/system/cpu/cpu* ; do
	[[ $(basename $cpu) =~ ^cpu[0-9]+$ ]] || continue

	# Reenable stuff in case we are rerunning this script.
	[ -f $cpu/online ] && echo 1 > $cpu/online
	if [ -f $cpu/cpufreq/scaling_governor ]; then
		chmod u+w $cpu/cpufreq/scaling_governor
	fi

	# Set governor to performance and do not allow changes later on.
	if [ -f $cpu/cpufreq/scaling_governor ]; then
		echo performance > $cpu/cpufreq/scaling_governor
		chmod a-w $cpu/cpufreq/scaling_governor
	fi

	# Disable all but one thread on each core.
	core_id=$(cat $cpu/topology/core_id)
	if [[ ${core_ids[$core_id]} ]]; then
		echo 0 > $cpu/online
	else
		core_ids[$core_id]=1
	fi
done

DIR_INTEL=/sys/devices/system/cpu/intel_pstate
DIR_AMD=/sys/devices/system/cpu/cpufreq
if [ -d $DIR_INTEL ]; then
	# now disable turbo boost
	echo -n 1 > $DIR_INTEL/no_turbo || echo "Could not write to '$DIR_INTEL/no_turbo', ignoring for now..."
	if [ $(cat $DIR_INTEL/no_turbo) -ne 1 ]; then
		echo "Error: turboboost still enabled!"
		exit 1
	fi

	# increase freq from powersaving to normal, but don't overclock
	echo 100 > $DIR_INTEL/min_perf_pct
	echo 100 > $DIR_INTEL/max_perf_pct
elif [ -d $DIR_AMD ]; then
	# now disable boosting
	echo -n 0 > $DIR_AMD/turbo || echo "Could not write to '$DIR_AMD/turbo', ignoring for now..."
	if [ $(cat $DIR_AMD/turbo) -ne 0 ]; then
		echo "Error: boosting still enabled!"
		exit 1
	fi
else
	echo "Warning: kernel (turbo) boost config not found in '$DIR_INTEL' or '$DIR_AMD'."
fi
