#!/bin/bash -e

shopt -s extglob

declare -A core_ids

for cpu in /sys/devices/system/cpu/cpu* ; do
	[[ $(basename $cpu) =~ ^cpu[0-9]+$ ]] || continue

	# Reenable stuff in case we are rerunning this script.
	chmod u+w $cpu/cpufreq/scaling_governor
	[ -f $cpu/online ] && echo 1 > $cpu/online

	# Set governor to performance and do not allow changes later on.
	echo performance > $cpu/cpufreq/scaling_governor
	chmod a-w $cpu/cpufreq/scaling_governor

	# Disable all but one thread on each core.
	core_id=$(cat $cpu/topology/core_id)
	if [[ ${core_ids[$core_id]} ]]; then
		echo 0 > $cpu/online
	else
		core_ids[$core_id]=1
	fi
done

DIR=/sys/devices/system/cpu/intel_pstate
if [ -d $DIR ]; then
	# now disable turbo boost
	echo -n 1 > $DIR/no_turbo

	# increase freq from powersaving to normal, but don't overclock
	echo 100 > $DIR/min_perf_pct
	echo 100 > $DIR/max_perf_pct
else
	echo "Warning: kernel turbo boost config not found in '$DIR'."
fi
